name: CI

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: tests
    uses: ./.github/workflows/tests.yml
    with:
      sha: ${{ needs.setup.outputs.sha }}
    secrets: inherit

  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - run: env
  
  event_file:
    name: "Upload event file"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ci-event-file
          path: ${{ github.event_path }}
