name: CI

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - name: Upload event file 
        uses: actions/upload-artifact@v3
        with:
          name: ci-event-file
          path: ${{ github.event_path }}
  tests:
    name: tests
    uses: ./.github/workflows/tests.yml
    with:
      sha: ${{ needs.setup.outputs.sha }}
    secrets: inherit
    needs: setup

  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - run: env
